### ISSUE TITLE
Support added

### ISSUE THREAD

**Issue by mkll** [mdznr/NetworkActivityIndicator#2]
Hi Matt! I just want to inform you that I've added support of your API to my NSURLConnection wrapper (https://github.com/mkll/ZMHTTPRequest).

**Comment by mdznr** [comment]
Wow, that's great! Thanks for letting me know. Keep me up to date when you're further in development. The project could also use some more documentation (and a complete README).
I'm happy to see you like my little fix for the network activity indicator!

**Comment by mkll** [comment]
Thank you. :) Your "little fix" is in fact a great thing. You are absolutely right to note that the Apple's implementation is far from ideal. This indicator can be adequately and accurately managed only if all parts of the application are under control of the developer. But as soon as we begin to use third-party components that control the indicator independently, then we are faced with a problem. It's absolutely necessary to have a single "point of control" in a whole application and your solution is exactly what we need.

I believe that your "fix" definitely requires the promotion and wide dissemination among developers. So I made ​​a small contribution to it. :)

**Comment by mdznr** [comment]
I haven’t looked into it too much, but this might include stuff in Apple’s own frameworks, like MPMoviePlayerController.
